### ISSUE TITLE
suggestion: consider adding golangci-lint to your repository and CI

### ISSUE THREAD

**Issue by ccoVeille** [nobe4/gh-not#221]
I launched golangci-lint with a lot of linters on your code.

It reported a bunch of issues

130 issues:
* errcheck: 1
* errorlint: 4
* gci: 17
* gocritic: 4
* gosimple: 1
* ineffassign: 1
* misspell: 8
* perfsprint: 3
* revive: 80
* staticcheck: 1
* thelper: 6
* unused: 1
* usestdlibvars: 3

May I open PR to fix them ? And add golangci-lint to your repository and CI ?

**Comment by nobe4** [comment]
Hi @ccoVeille, thanks for this and #222!

Yes, please open a PR with it 🎉.

If you can update the existing [`lint` job](https://github.com/nobe4/gh-not/blob/main/.github/workflows/ci.yml#L43-L71), that'd be great, but if not, please add a new job in the same file.

**Comment by ccoVeille** [comment]
I see you are using deadcode

https://github.com/nobe4/gh-not/blob/3bff3960e723bc2c8381ef06b0ea39a070aa95df/.github/workflows/ci.yml#L73-L93

golangci-lint supersedes it with `unused` linter

https://golangci-lint.run/usage/linters/#unused

Source is here https://github.com/dominikh/go-tools/tree/master/unused

Do you agree to remove deadcode from the CI then ?

**Comment by nobe4** [comment]
Interesting, let's leave both for now :)

I'll need to look more closely at what `unused` does and if it's a complete replacement of `deadcode`.

**Comment by nobe4** [comment]
@ccoVeille consider adding only the CI job for now, and I'll dedicate time to fix the issues :)
